FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD ["npm", "run", "start"]

# docker run -p 3000:3000 -it -v /usr/src/app/node_modules -v ${pwd}:/usr/src/app deankim0507/reactapp:latest